---
title: "unused codes"
output: html_document
date: "2024-06-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

unused code in the STAT101 apps


# one numerical vairiable

## boxplot using ggplot
was to draw with ggplot, then `plotly_build(p)`
```{r}
# in shiny server.r
boxplot <- eventReactive(input$updateBoxPlotButton, {
  df = df_raw()[c(input$num1)]
  
  # p <- ggplot(df_sub(), aes_string(y = names(df_sub())[1], x = 0)) +
  p <- ggplot(df, aes_string(y = input$num1, x = 0)) +
    # geom_jitter(shape = 18, alpha = 0.5, color = "black", fill = "grey", width = 0.25) +
    geom_boxplot() +
    coord_flip()
  
  
  fig <- plotly_build(p)
  fig$x$data[[1]]$marker$opacity <- 0.5
  ## customise the boxplot settings:
  # if boxplot comes later after the jitters, then use data[[2]]
  # if the boxplot is the first layer, then data[[1]]
  fig$x$data[[1]]$fillcolor <- input$colBoxFill
  fig$x$data[[1]]$line$color <- input$colBoxLine
  
  
  boxOutput <-  plot_ly(type = "box") %>% 
    hide_colorbar() %>% 
    add_trace(x = mean(df[,1],na.rm = TRUE),  y = 0,
              type = "scatter", mode = "marker",
              marker = list(symbol = "x",
                            size = 10,
                            color = "deepskyblue"),
              hoverinfo = "text",
              text = ~paste("Mean: ",round(mean(df[,1],na.rm = TRUE),2), sep="")) %>% 
    layout(plot_bgcolor= input$colBackground, #'#e5ecf6',
    title = titleBox(),
    xaxis = list(title = xLabBox(),
                 showgrid = T,
                 gridcolor = 'ffff',
                 automargin = TRUE
    ),
    yaxis = list(gridcolor = 'ffff',
                 showgrid = T,
                 title = yLabBox(),
                 ticklen = 0,
                 showticklabels=TRUE,
                 automargin = TRUE
    ),
    margin = list(
      l = 50,
      r = 25,
      b = 25,
      t = 75,
      pad = 20
    )
    )%>%
    config(modeBarButtons = list(list("toImage")),
           displaylogo = FALSE)
  
  return(boxOutput)
})

output$boxPlot <- renderPlotly({
  boxplot()
})


```

## quartiles algorithm
```{r}
# in ui.r
radioGroupButtons(
  inputId = "num1BoxAlgorithm",
  label = "Quartiles Algorithm:",
  choices = c("Linear", 
              "Inclusive", 
              "Exclusive"),
  status = "primary",
  checkIcon = list(
    yes = icon("ok", 
               lib = "glyphicon"),
    no = icon("remove",
              lib = "glyphicon"))
)

# in server.r
# boxOutput <-  plot_ly(type = "box") %>% 
#   # the box
#   add_boxplot(x = ~df[,1], 
#               # can without a y value for the box itself, but with it can be helpful for the mean point
#               y = input$num1,
#               boxpoints = 'outliers',
#               jitter = 0.5,
#               pointpos = 0,
#               line = list(color = input$colBoxLine),
#               fillcolor = input$colBoxFill,
quartilemethod = tolower(input$num1BoxAlgorithm),
#             showlegend = FALSE,
#             # to scrap off the "trace 0" tag
#             hoverinfo = 'x'
# )%>% ......


```


```{r}
df = mtcars
#using ggplot, user can set the bin numbers as they wish but sometimes the bin is not algined to the ticks well

# range = range(df_sub(), na.rm = TRUE)
#
# binWidth = (range[2]-range[1])/(input$binNums-1)

axisMin = min(df[,1])
axisMax = max(df[,1])
histStep = 10^(floor(
  log10(
    axisMax - axisMin
    # max(df,na.rm = TRUE)-
    #   min(df,na.rm = TRUE)
  )
)-1)

histBinNums <- 10
# 
# axisEnd = ceiling(max(df,na.rm = TRUE)/histStep)*histStep
# axisStart = floor(min(df,na.rm = TRUE)/histStep)*histStep
axisEnd = ceiling(axisMax/histStep)*histStep
axisStart = floor(axisMin/histStep)*histStep

hist <- ggplot(data = df, mapping = aes_string(x = names(df)[1])) +
  geom_histogram( breaks = seq(axisStart, axisEnd, length.out = histBinNums+1),
                  # bins = input$binNums,
                  fill = "salmon", color = "black") +
  theme(
    plot.margin = margin(0.7, 0.2, 0.2, 0.2, "cm"),
    panel.grid=element_blank()
  )
hist

# +
#     scale_x_continuous(
#         breaks = round(seq(range[1]-binWidth/2, range[2]-binWidth/2,by = binWidth)),
#         labels = round(seq(range[1], range[2], by = binWidth), 1),
#         guide = guide_axis(check.overlap = TRUE))

aa <- ggplotly(hist)
axisSeq <- seq(min(aa$x$data[[1]]$x-aa$x$data[[1]]$width/2),
               max(aa$x$data[[1]]$x+aa$x$data[[1]]$width/2),
               by = max(round(histBinNums/10),1)*aa$x$data[[1]]$width[1])

plotHist <- aa %>%
  style(hoverinfo = 'none') %>%
  add_trace(x=aa$x$data[[1]]$x,
            y=aa$x$data[[1]]$y,
            color = "salmon", #I(input$colFill),
            alpha = 0.01,
            type = 'bar',
            text = paste0(
              "range: (", round(aa$x$data[[1]]$x-aa$x$data[[1]]$width/2, 2), ", ",
              round(aa$x$data[[1]]$x+aa$x$data[[1]]$width/2, 2), "]", 
              "<br>frequency: ", aa$x$data[[1]]$y
              # "lower bound: ", round(aa$x$data[[1]]$x-aa$x$data[[1]]$width/2, 2),
              # "<br>upper bound: ", round(aa$x$data[[1]]$x+aa$x$data[[1]]$width/2, 2),
              # "<br>frequency: ", aa$x$data[[1]]$y
            ),
            hoverinfo="text") %>%
  layout(plot_bgcolor = '#e5ecf6',
  title = "titleHist()",
  xaxis = list(
    title = "xLabHist()",
    ticks="inside",
    ticktext = round(axisSeq,1),
    tickvals = axisSeq,
    tickmode = "array",
    tickangle = 45,
    showgrid = T,
    gridcolor = 'ffff'
  ),
  yaxis = list(
    title = "yLabHist()",
    gridcolor = 'ffff',
    showgrid = T,
    title = "Frequency",
    ticktext = round(seq(0, max(aa$x$data[[1]]$y),length.out = 6)),
    tickvals = seq(0, max(aa$x$data[[1]]$y),length.out = 6),
    tickmode = "array")
  ) %>%
  config(modeBarButtons = list(list("toImage")),
         displaylogo = FALSE)

plotHist$width
aa$width
```








